In [1]:
import pandas as pd

In [55]:
pd_data = pd.read_csv('./datas/vaccination_bytype_20210719.csv',encoding='euc-kr',thousands=',')

In [56]:
pd_data

,일자,전체 1차,전체 완료,아스트라제네카 1차,아스트라제네카 완료\n(AZ-PF교차포함),화이자 1차,화이자 완료\n(AZ-PF교차미포함),얀센 1차(완료),모더나 1차,모더나 완료
0,2021-07-18,16133084,6565472,10401113,1727038,4539060,3708491,1129705,63206,238
1,2021-07-17,16130726,6565026,10401113,1726594,4536702,3708489,1129705,63206,238
2,2021-07-16,16096296,6528453,10401093,1699632,4502292,3698878,1129705,63206,238
3,2021-07-15,15961768,6350018,10400770,1574871,4368118,3645442,1129705,63175,0
4,2021-07-14,15838836,6207909,10400306,1472394,4245650,3605810,1129705,63175,0
...,...,...,...,...,...,...,...,...,...,...
138,2021-03-02,90484,0,88957,0,1527,0,0,0,0
139,2021-03-01,24071,0,23173,0,898,0,0,0,0
140,2021-02-28,22596,0,21991,0,605,0,0,0,0
141,2021-02-27,21732,0,21414,0,318,0,0,0,0
142,2021-02-26,20308,0,20308,0,0,0,0,0,0

In [81]:
type(pd_data.iloc[0:,3])
len(pd_data.iloc[0:,3])
type(pd_data.iloc[142,3])

numpy.int64

In [113]:
azones =[];
aztwos =[];
hzones =[];
hztwos =[];
yss =[];
mdones =[];
mdtwos=[];

for index in range(0,142):
    azones.append(pd_data.iloc[index,3]-pd_data.iloc[index+1,3])
    aztwos.append(pd_data.iloc[index,4]-pd_data.iloc[index+1,4])
    hzones.append(pd_data.iloc[index,5]-pd_data.iloc[index+1,5])
    hztwos.append(pd_data.iloc[index,6]-pd_data.iloc[index+1,6])
    yss.append(pd_data.iloc[index,7]-pd_data.iloc[index+1,7])
    mdones.append(pd_data.iloc[index,8]-pd_data.iloc[index+1,8])
    mdtwos.append(pd_data.iloc[index,9]-pd_data.iloc[index+1,9])

azones.append(0)
aztwos.append(0)
hzones.append(0)
hztwos.append(0)
yss.append(0)
mdones.append(0)
mdtwos.append(0)

In [88]:
pd_data['아스트라제네카1차 일일접종량'] =azones
pd_data['아스트라제네카 완료 일일접종량'] =aztwos
pd_data['화이자 1차 일일접종량'] =hzones
pd_data['화이자 완료 일일접종량'] =hztwos
pd_data['얀센 완료 일일접종량'] =yss
pd_data['모더나 1차 일일접종량'] =mdones
pd_data['모더나 완료 일일접종량'] =mdtwos

In [110]:
az_pd = pd_data[['일자','아스트라제네카 1차','아스트라제네카 완료\n(AZ-PF교차포함)','아스트라제네카1차 일일접종량','아스트라제네카 완료 일일접종량']]
az_pd['종류'] = '아스트라제네카'

hz_pd = pd_data[['일자','화이자 1차','화이자 완료\n(AZ-PF교차미포함)','화이자 1차 일일접종량','화이자 완료 일일접종량']]
hz_pd['종류'] = '화이자'

md_pd = pd_data[['일자','모더나 1차','모더나 완료','모더나 1차 일일접종량','모더나 완료 일일접종량']]
md_pd['종류'] = '모더나'

ys_pd = pd_data[['일자','얀센 1차(완료)','얀센 완료 일일접종량']]
ys_pd['종류'] = '얀센'
ys_pd['백신 1차 누적 접종량'] =0
ys_pd['백신 1차 일일 접종량']=0

c:\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

c:\python\python36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
c:\python\python36\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

c:\python\python36\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
c:\python\python36\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
c:\python\python36\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [111]:
az_pd.rename(columns={'아스트라제네카 1차':'백신 1차 누적 접종량','아스트라제네카 완료\n(AZ-PF교차포함)':'백신 완료 누적 접종량','아스트라제네카1차 일일접종량':'백신 1차 일일 접종량','아스트라제네카 완료 일일접종량':'백신 완료 일일 접종량'},inplace=True)
hz_pd.rename(columns={'화이자 1차':'백신 1차 누적 접종량','화이자 완료\n(AZ-PF교차미포함)':'백신 완료 누적 접종량','화이자 1차 일일접종량':'백신 1차 일일 접종량','화이자 완료 일일접종량':'백신 완료 일일 접종량'},inplace=True)
md_pd.rename(columns={'모더나 1차':'백신 1차 누적 접종량','모더나 완료':'백신 완료 누적 접종량','모더나 1차 일일접종량':'백신 1차 일일 접종량','모더나 완료 일일접종량':'백신 완료 일일 접종량'},inplace=True)
ys_pd.rename(columns={'얀센 1차(완료)':'백신 완료 누적 접종량','얀센 완료 일일접종량':'백신 완료 일일 접종량'},inplace=True)

c:\python\python36\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,